version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000 # S3 API
      - 9090:9090 # Console
    environment:
      MINIO_CONFIG_ENV_FILE: /etc/config.env
    secrets:
      - source: minioSecret
        target: /etc/config.env
    volumes:
      - minioData:/mnt/data
    command: 'server /mnt/data --console-address ":9090"'
  # Init Minio Bucket
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    # environment:
      # MINIO_ROOT_USER: /run/secrets/minio_root_user # Not Working, see why
      # MINIO_ROOT_PASSWORD: /run/secrets/minio_root_password  # Not Working, see why
    secrets:
      - minio_root_user
      - minio_root_password
    entrypoint: >
      /bin/sh -c "
      echo ${MINIO_ROOT_USER};
      /usr/bin/mc alias set myminio http://minio:9000 admin NotAdmin123*;
      /usr/bin/mc mb myminio/docker-registry;
      mc ls myminio;
      exit 0;
      "
  # Registry Docker
  registry:
    image: registry:2
    depends_on:
      - minio
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml


volumes:
  minioData:

secrets:
  minioSecret:
    file: ./minio/config.env
  minio_root_password:
    file: minio_root_password.txt
  minio_root_user:
    file: minio_root_user.txt